name: minimal_pos
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  google_fonts: 4.0.3
  faker: 2.1.0
  hive: 2.2.3
  hive_flutter: 1.1.0
  path_provider: 2.0.14
  build_runner: 2.3.3
  hive_generator: 2.0.0
  grouped_listview: 0.0.2
  grouped_list: 5.1.2
  pdf: 3.10.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

